// export const BE_DOMAIN = 'http://be.tavivu.net'
export const BE_DOMAIN = 'http://localhost:8000'
export const BE_API_DOMAIN = `${BE_DOMAIN}/api`
export const BE_API_TOURS_INTERNATIONAL = `${BE_API_DOMAIN}/tours-international`
export const BE_API_TOURS_IN_COUNTRY = `${BE_API_DOMAIN}/tours-in-country`
export const BE_API_TOUR_DETAIL = `${BE_API_DOMAIN}/tours`
export const BE_API_HOME = `${BE_API_DOMAIN}/home`
export const BE_API_CONTACT = `${BE_API_DOMAIN}/contact`
export const BE_API_ABOUT = `${BE_API_DOMAIN}/about`
export const BE_API_PAGE = `${BE_API_DOMAIN}/pages`
export const BE_API_CONFIGS = `${BE_API_DOMAIN}/configs`
export const BE_API_SEND_CONTACT = `${BE_API_DOMAIN}/contacts/send`
export const BE_API_SEND_SERVICE = `${BE_API_DOMAIN}/services/send`
export const BE_API_ORDER_TOUR = `${BE_API_DOMAIN}/tour-order/send`
export const BE_API_IMAGES = `${BE_API_DOMAIN}/images`
